### ISSUE TITLE
Не указаны зависимости для бота

### ISSUE THREAD

**Issue by Alvarus** [progserega/matrix_redmine_bot#2]
Полезно будет в инструкциях сразу указать зависимости, чтобы не приходилось их вычислять наощупь.
На текущий момент вижу следующие модули:

```
matrix_client
systemd_watchdog
redminelib
imapclient
```

redminelib в debian/ubuntu есть в репозитории как `python3-redminelib`. Остальное необходимо ставить через pip.

**Comment by progserega** [comment]
добавил https://github.com/progserega/matrix_redmine_bot/commit/865d51c35593d64e47a10b53f4eba4eaa1edf063
спасибо!
